version: '3.8'

services:
  command-service:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "${PORT}:3000" # Utilise la variable d'environnement PORT définie dans .env
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - mongo
    command: "node src/index.js" # Assure-toi que ce chemin correspond à ton fichier de démarrage
  
  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
