services:

  user-service:
    build:
      context: ./users
      dockerfile: Docker/node/Dockerfile
    ports:
      - "3001:3000"
    volumes:
      - ./user-service:/home/node/app
    networks:
      - app-network
    depends_on:
      - user-db

  user-db:
    image: mongo:latest 
    container_name: user-mongo
    ports:
      - "27017:27017"
    volumes:
      - user-db-data:/data/db
    networks:
      - app-network

volumes:
  time-db-data:
  user-db-data:

networks:
  app-network:
    driver: bridge
