services:
  user-service:
    build:
      context: ./users
      dockerfile: Docker/node/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./users:/home/node/app
      - /home/node/app/node_modules
    networks:
      - app-network
    depends_on:
      - user-db

  user-db:
    image: mongo:latest
    container_name: user-mongo
    ports:
      - "27017:27017"
    volumes:
      - user-db-data:/data/db
    networks:
      - app-network

  cart_service:
    build:
      context: ./cart
      dockerfile: Docker/node/Dockerfile
    ports:
      - "3003:3003"
    volumes:
      - ./cart:/home/node/app
      - /home/node/app/node_modules
    networks:
      - app-network
    depends_on:
      - cart-db
  front:
    build:
      context: ./front
      dockerfile: Docker/Dockerfile
    command: npm run dev

    ports:
      - "5173:5173"
    volumes:
      - ./front:/home/node/app
      - /home/node/app/node_modules
    networks:
      - app-network

  cart-db:
    image: mongo:latest
    container_name: cart-mongo
    ports:
      - "27020:27017"
    volumes:
      - cart-db-data:/data/db
    networks:
      - app-network

volumes:
  user-db-data:
  cart-db-data:

networks:
  app-network:
    driver: bridge
