services:

  apigateway-service:
    build:
      context: ./api-gateway
      dockerfile: Docker/node/Dockerfile
    ports:
      - "3005:30005"
    volumes:
      - ./api-gateway:/home/node/app
      - /home/node/app/node_modules
    networks:
      - app-network
    


networks:
  app-network:
    driver: bridge