services:

  cart_service:
    build:
      context: ./cart
      dockerfile: Docker/node/Dockerfile
    ports:
      - "3003:3003"
    volumes:
      - ./cart:/home/node/app
      - /home/node/app/node_modules
    networks:
      - app-network
    depends_on:
      - cart-db

  cart-db:
    image: mongo:latest
    container_name: cart-mongo
    ports:
      - "27020:27017"
    volumes:
      - cart-db-data:/data/db
    networks:
      - app-network

volumes:
  cart-db-data:

networks:
  app-network:
    driver: bridge