services:
  order-service:
    build:
      context: ./order
      dockerfile: /docker/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - order-db
    networks:
      - app-network
  
  order-db:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - order-db-data:/data/db
    networks:
      - app-network

volumes:  
  order-db-data:

networks:
  app-network:
    driver: bridge