services:
  mongo:
    image: mongo
    ports:
      - "27020:27017"
    volumes:
      - mongo-data:/data/db
  cart_service:
    build: .
    ports:
      - "3003:3003"
    environment:
      - MONGO_URI=mongodb://mongo:27017/Cart
    depends_on:
      - mongo

volumes:
  mongo-data:
