### Delete User
POST http://localhost:3001/users/delete
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY3MWY2YTNiMzQxZTVkOGE1ODAzMzFjNiIsInJvbGUiOnRydWUsImlhdCI6MTczMDExMzIwMiwiZXhwIjoxNzMwMTE2ODAyfQ.bwvVgi0Ejr3ROcvP5VYCfQAPUDkjg5-UYdemB3Iz_5g

{
  "_id": "671f6a3b341e5d8a580331c6"
}